### ISSUE TITLE
[EPIC Testing] Plan recurring automatic CI testing for 3 to 5 major K8s cloud providers

### ISSUE THREAD

**Issue by taylor** [cnti-testcatalog/testsuite#1535]
Run ci against major platforms on a recurring basis (eg. weekly)

Possible providers:
- Microsoft Azure
- Google Cloud
- AWS

Todo: 
- [ ] List providers in this ticket for initial CI testing and plans
- [ ] Plan and brainstorm initial CI needs to support the multiple provider testing
- [ ] Create tickets for each provider to support recurring automatic CI testing
    - Note: Implementation will happen on each provider specific ticket as they are added
