### ISSUE TITLE
[MAINTENANCE] Lower the number of github runners in use at Equinix

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1777]
**Describe the software update**
Need to bring the number of total instances and machines in use as github runners down.

**Describe why update is needed**
Equinix is asking us to lower our overall resources used.

**Additional context**
We can perhaps bump the existing runners to the next level for more resources to create more virtual github runners while lowering the number of total machines in use to lower the overall cost and resources in use while still maintaining build times for development.

```[tasklist]
### Tasks
- [x] delete all but 3 runners
- [x] run the tests to make sure the CI works
```

**Following runners we are keeping, others will be deleted:**
-  github-runner2
-  github-runner3
-  github-runner4

**Comment by lixuna** [comment]
Task:

- [ ] Prepare a plan for addressing how to reduce the number of Github runners in the CNCF CIL hosted at Equinix 
- [ ] Reference: active runners at https://console.equinix.com/projects under CNCF Organization (3 projects)

<img width="271" alt="Screenshot 2023-11-29 at 4 14 45 PM" src="https://github.com/cncf/cnf-testsuite/assets/11701267/8a9593ea-cf1f-447d-96e1-8ff2dcabfcdd">

**Comment by lixuna** [comment]
a note on Managed Arm CI for CNCF projects (https://actuated.dev/blog/arm-ci-cncf-ampere)
- Currently the cnf test suite runs on x86 servers

**Comment by agentpoyo** [comment]
I turned off github runners labeled 5-11. We'll see performance on CI before terminating. @denverwilliams @lixuna @taylor

**Comment by lixuna** [comment]
List of instances that have been terminated:

1. github-runner5
2. github-runner6
3. github-runner7
4. github-runner8
5. github-runner9
6. github-runner10
7. github-runner11
8. cnfqa1
9. akash-rhel8
10. cncf-testsuite-mk8s1
11. cncf-testsuite-test1 
12. 
13. 

cnfqa1 has been terminated

**Comment by agentpoyo** [comment]
All runners except 3 have been terminated. No AC required.
