### ISSUE TITLE
[Workload] 5g Authentication test

### ISSUE THREAD

**Issue by wavell** [cnti-testcatalog/testsuite#1803]
## This test is for the 5g core only

requires (https://github.com/cncf/cnf-testsuite/issues/1065)
and (https://github.com/cncf/cnf-testsuite/issues/1806)

**Is your workload test idea related to a problem? Please describe.**
- In telecommunication systems, network operator allocate to each SIM card a unique identifier, known up to the 4G as an IMSI (International Mobile Subscriber Identity) and for the 5G as a  SUPI (Subscription Permanent Identifier). As authentication between a user and its  network provider is based on a shared symmetric key, it can only take place after user identification. However, if the IMSI/SUPI values are sent in plaintext over the radio access link, then users can be identified, located and tracked using these permanent identifiers.
An active man-in-the-middle adversary can intentionally simulate this scenario to force an unsuspecting user to reveal its long-term identity. These attacks are known as “IMSI catching”  attacks and persist in today’s mobile networks including the 4G LTE/LTE-Adv.  https://www.techplayon.com/5g-identifiers-supi-and-suci/

**Describe the solution you'd like**
-  5G defines three authentication methods—5G-AKA, EAP-AKA’, and EAP-TLS.  One or all of the methods should be tested to confirm that 5g authentication is present

**Test Category Name**
- ADD Interoperability (e.g. State, Security, etc from [README](https://github.com/cncf/cnf-testsuite/blob/main/README.md#cnf-testsuite))

**Type of test (static or runtime)**
- runtime

https://github.com/jimtangshfx/5G_ciphered_NAS_decipher_tool
https://github.com/jimtangshfx/5G_ciphered_NAS_decipher_tool/blob/master/src/5G_NAS_decipher_3gpp_standard.py#L138C24-L138C42

To check if a connection is successful in wireshark, look for:
````
"e212.imsi": "001010000000009",
````

to check if a connection is using 5g authencticaiton, look for:

````
# if ID type is SUCI:
if packet.ngap.nas_5gs_mm_type_id == '1':
````

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

```[tasklist]
### Tasks
- [ ] Create a method for identifying (or allowing the user to designate) a 5G core's pods
- [ ] Use the UERANSIM to the traffic to the core
- [ ] Add Tshark to the cluster tools
- [ ] Use tshark to capture the network traffic to the core
- [ ] Alternate to tshark: execute a replay from an existing pcap file with the proper network traffic
- [ ] Verify that there exists a packet wherein the payload has ngap.nas_5gs_mm_type_id == '1'
```
