### ISSUE TITLE
[RESEARCH] Prepare to Transfer CNF Test Suite repo to new GitHub org

### ISSUE THREAD

**Issue by lixuna** [cnti-testcatalog/testsuite#1851]
**Describe the update:**
- Transfer CNF Test Suite away from CNCF org

**Describe why update is needed**
- CNF Test Suite (and CNCF’s related Cloud Native Telco efforts) moving to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))

**Additional context**
- https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Tasks:**

- [ ] Create new issues for tasks related to changing the github org 
- [ ] Document code that will need to be changed in this repository, for example:
  - [ ] crystal lang dependency file
  - [ ] yaml config file
  - [ ] crystal source code
- [ ] Document changes needed for github automation for merges 
- [ ] Document changes needed for github automation for pull requests
- [ ] Document other changes that will be needed before/after moving from /cncf to a new org
- [x] Remove existing github runners prior to migration; deploy new github runners after migration for CI/CD builds

**Comment by taylor** [comment]
**End User updates or notice**
- Update configuration that points to the test suite repo URL to it's new URL after transfer, such as
    - Existing clones .git/config (or a new clone is needed)
    - CI plugins such as Jenkins: https://plugins.jenkins.io/github/
- Increased time for QA of PRs (Pull Requests): The cnf-testsuite's internal repository automated CI will be disabled for some time after transfer so the maintainers will be delayed on QA as manual testing is required.

**Comment by agentpoyo** [comment]
Github runners are not working like they should. Seeing kind clusters failing to delete for cleanup so the spec fails, some never finish running (core and platform are biggest culprit I've seen so far), etc. Continuing to investigate the issues. @HashNuke @denverwilliams @wavell

**Comment by lixuna** [comment]
GitHub transfer completed. Please create new issues for any problems/bugs found as a result of the transfer

**Comment by lixuna** [comment]
#1874
